alias orbital='cd ~/projects/vr/code/development/orbital'
alias orb='cd ~/projects/vr/code/development/orbital'
alias vr='cd ~/projects/vr/code/development/vr'
alias ll='ls -las'
alias bf='cd ~/projects/billfloat/code/development/billfloat'
alias bfs='cd ~/projects/billfloat/code/development/backend_services'
alias rc='script/console'
